Tweak docs to guide users towards correct API usage
BurntSushi/jiff pull request #134
Opened 2024-09-19 07:36 UTC by Plecra

The end goal with this PR is to adjust the documentation to make the semantics of the library as clear as possible.

I've started with just a tiny change to set a foundation, updating the documentation comment to define Timestamp wrt UNIX time.

citations, since my only msgs so far are on discord:

- `now` uses the value constructed by `duration_since(EPOCH)`, which is [defined as POSIX time](https://doc.rust-lang.org/stable/std/time/struct.SystemTime.html#associatedconstant.UNIX_EPOCH)
  > duration_since(UNIX_EPOCH).unwrap().as_secs() returns the number of non-leap seconds since the start of 1970 UTC. This is a POSIX time_t (as a u64), and is the same time representation as used in many Internet protocols.
  this can also be tested experimentally by printing the `Timestamp::now().as_nanos()`
- `Display for Timestamp` prints the corresponding date to an input unix time.
  this can also be tested by printing `format!("{}", Timestamp::new(24 * 60 * 60 * (365 * 30+ (30 / 4)) , 0))`, which is 22 seconds faster than it should be

2024-09-19 08:16 UTC, Plecra commented
On https://github.com/BurntSushi/jiff/issues/7#issuecomment-2359423476, I wanna make the most compelling case I can 😁 

Which part of this should I elaborate on?

- "Jiff is a datetime library for Rust that encourages you to jump into the pit of success", so I'm assuming the API should be structured in a way that makes it easy to find the right API when you want to do something
- It is common for users to write the `let start = now(); f(); now() - start` pattern
- The current API presents `Timestamp` as entirely appropriate (`now()` and `Sub`) for the measurement pattern
- But this implementation is obviously wrong
  - in that it will return a completely incorrect result in normal operating conditions 
  - *and* 1 second is a massive error for plenty of cases of this measurement pattern


Youve said that

> I also think that a lot of the trouble and bugs that come from leap seconds aren't necessarily because of datetime libraries not handling them, but rather, because programmers have assumed that their system time is monotonically increasing. Jiff doesn't provide any monotonic guarantees because it's a library for dealing with human time.

so this is entirely fine semantically, but I do not agree that it's a "pit of success", the library immediately lures naive users down the wrong path by presenting them with the classic failure mode. We *cant* write code that calculates deltas because we can't "assume that our system time is monotonically increasing", but jiff offers that incorrect behaviour via the most accessible API!

2024-09-19 12:32 UTC, BurntSushi commented on src/timestamp.rs
> +/// A timestamp is always in the UNIX timescale.
I wrote this on discord:

well... that's kinda the thing, right. the imprecision of language in this area, and especially with things like UTC, is so widespread that to not to conform to it can wind up being more misleading than not. i mentioned above that UTC is a time scale, and yet, it is seemingly commonly used _as if_ it were a **time zone**. that is, UTC is used to describe the case where the offset is zero. from RFC 9557:

>    UTC Offset:  Difference between a given local time and UTC, usually
>       given in negative or positive hours and minutes.  For example,
>       local time in the city of New York, NY, USA in the wintertime in
>       2023 was 5 hours behind UTC, so its UTC offset was -05:00.

so when you talk about something like `2024-09-19T08:11:00Z`, you can say that's a "specific instant in time, expressed in UTC." and in this context, it works correctly, because the representation is theoretically unambiguous. that is, there's no reason why you can't have `2024-06-30T23:59:60Z`. but as soon as you parse that into a Unix timestamp, the notion of it being UTC doesn't really apply any more. instead, it's a _Unix timestamp_. and of course, Unix time forgos leap seconds. _nevertheless_, the concept of "offset from UTC" still carries over. indeed, this is a thing:

```
$ ls -l /usr/share/zoneinfo/UTC
-rw-r--r-- 8 root root 114 Sep  6 10:07 /usr/share/zoneinfo/UTC
```

despite the fact that tzdb uses Unix time just about everywhere (except for `/usr/share/zoneinfo/right`). because in this context, "a timestamp in UTC" is being used to say something about its _offset_ and not its _time scale definition_.

2024-09-19 12:33 UTC, BurntSushi commented on src/timestamp.rs
> +/// A timestamp is always in the UNIX timescale.
So maybe a clearer way of writing this is:

> A timestamp is always in the Unix timescale with a UTC offset of zero.

2024-09-19 12:48 UTC, BurntSushi commented
> so this is entirely fine semantically, but I do not agree that it's a "pit of success", the library immediately lures naive users down the wrong path by presenting them with the classic failure mode. We cant write code that calculates deltas because we can't "assume that our system time is monotonically increasing", but jiff offers that incorrect behaviour via the most accessible API!

Pit of success is a pithy goal of the library. It's a design principle. Jiff does not and will not meet that goal in every case, and it will sometimes be in tension with other design goals. You seem to be suggesting that Jiff not offer a way to ask for the current time and provide an easy way to calculate the difference between two times. Like, this seems completely bonkers to me.

2024-09-20 11:38 UTC, BurntSushi requested changes

2024-09-20 11:38 UTC, BurntSushi commented on src/timestamp.rs
> +/// A timestamp is always in the UNIX timescale with a UTC offset of zero.
```suggestion
/// A timestamp is always in the Unix timescale with a UTC offset of zero.
```

2024-09-22 12:53 UTC, BurntSushi approved these changes

2024-09-22 13:02 UTC, merged